### ISSUE TITLE
TypeError: this.allSharedForms.filter is not a function

### ISSUE THREAD

**Issue by teach404** [nextcloud/forms#2075]
**Describe the bug**

Opening the forms stab results in endless reload without loading the forms. This appears only to certain users so probably some forms are in the right "state".

I cant reproduce which shared form results to the error.

Console shows:

**To Reproduce**
1. Just open forms tab on the topbar

**Expected behavior**
Forms app should load

**Screenshots**

<img width="1073" alt="Snag_379dab" src="https://github.com/nextcloud/forms/assets/25730800/bdecbb68-87af-41ca-ac95-7d599a5c49ae">

**Nextcloud (please complete the following information):**
- Nextcloud-Version: 28.0.4
- Forms-Version: 4.2.2

**Desktop (please complete the following information):**
 - Browser chrome (123.0.6) and firefox (124.0.2) tested

**Browser log**

```
TypeError: this.allSharedForms is not iterable
    at s.archivedForms (forms-main.mjs?v=b026c9ab-18:8:168364)
    at e.get (vendor-DFuGXkIP.mjs:2:26754)
    at e.evaluate (vendor-DFuGXkIP.mjs:2:27754)
    at s.archivedForms (vendor-DFuGXkIP.mjs:2:41400)
    at s.Ll (forms-main.mjs?v=b026c9ab-18:8:174975)
    at Ga.e._render (vendor-DFuGXkIP.mjs:2:20940)
    at s.r (vendor-DFuGXkIP.mjs:2:30559)
    at e.get (vendor-DFuGXkIP.mjs:2:26754)
    at e.run (vendor-DFuGXkIP.mjs:2:27491)
    at ws (vendor-DFuGXkIP.mjs:2:32762)

ypeError: this.allSharedForms.filter is not a function
    at s.sharedForms (forms-main.mjs?v=b026c9ab-18:8:168281)
    at e.get (vendor-DFuGXkIP.mjs:2:26754)
    at e.evaluate (vendor-DFuGXkIP.mjs:2:27754)
    at s.sharedForms (vendor-DFuGXkIP.mjs:2:41400)
    at fn (forms-main.mjs?v=b026c9ab-18:8:172131)
    at o (vendor-DFuGXkIP.mjs:2:18761)
    at s.Ia [as _t] (vendor-DFuGXkIP.mjs:2:15994)
    at s.sr (forms-main.mjs?v=b026c9ab-18:8:81270)
    at Ga.e._render (vendor-DFuGXkIP.mjs:2:20940)
    at s.r (vendor-DFuGXkIP.mjs:2:30559)
```

**Comment by Chartman123** [comment]
Also confirmed on other instances, currently with 4.2.1, but as you pointed out still valid with 4.2.2

**Comment by Chartman123** [comment]
@teach404 Could you try to find out what's the difference between users that can load and see the forms list and those who can't?

**Comment by teach404** [comment]
Your works so i didnt looked deeper into it (regarding your questions)
